# Generated by Django 4.1.3 on 2022-12-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('channel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
