# Generated by Django 4.1.3 on 2023-02-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='site_name',
            field=models.CharField(max_length=255),
        ),
    ]
