# Generated by Django 4.1.3 on 2023-02-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presidentfact',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
