# Generated by Django 4.1.3 on 2023-02-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_presidentfact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
