# Generated by Django 4.1.3 on 2023-02-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
