# Generated by Django 4.1.3 on 2022-12-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['created_at'], 'verbose_name': 'Channel', 'verbose_name_plural': 'Channels'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['date'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='site_name',
            field=models.CharField(max_length=32),
        ),
    ]
