version: "3"

services:
  web:
    build: .
    container_name: stock_web
    command: poetry run python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on: 
      - db
    env_file:
      - ./.env
    platform: linux/amd64
  db:
    image: postgres:16.1
    container_name: stock_db
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    platform: linux/amd64

volumes:
  postgres_db:
