version: "3"

services:
  worker:
    build: .
    command: poetry run python manage.py runserver 0:8000
    ports:
    - "8000:8000"
    volumes:
    - .:/code
    depends_on: 
    - db
  db:
    image: postgres
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres