version: "3"

services:
  worker:
    build: .
    command: poetry run python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on: 
      - db
    env_file:
      - ./.env
    platform: linux/amd64
  db:
    image: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
        POSTGRES_DB: ${postgres_database}
        POSTGRES_USER: ${postgres_username}
        POSTGRES_PASSWORD: ${postgres_password}
    ports:
      - "5432:5432"
    platform: linux/amd64

volumes:
  postgres_db: