version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock_web
    command: poetry run python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on: 
      - db
    env_file:
      - ./.env
    platform: linux/amd64
  db:
    image: postgres
    container_name: stock_db
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
        POSTGRES_DB: ${POSTGRES_DATABASE}
        POSTGRES_USER: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    platform: linux/amd64

volumes:
  postgres_db:
