# Generated by Django 4.1.3 on 2023-03-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_email',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Kakao Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
